title: Jungwoo's personal blog
author: jglee0814
email: jglee0814@g.skku.edu
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://jglee0814.github.io/"
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Jungwoo's personal blog
  tagline: Developer. College student
  date_format: "%b %-d, %Y"
  style: purple
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: jglee0814
    github:  jglee0814
    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

remote_theme: samarsault/texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

#theme: texture

future: true
